# fly.toml app configuration file generated for search-red-snow-3231 on 2025-08-02T19:22:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'search-red-snow-3231'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
